[project]
name = "incident-response"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "a2a-sdk @ git+https://github.com/Tehsmash/a2a-python@feat/send-live-message",
    "slima2a @ git+https://github.com/agntcy/slim-a2a-python@feat/send-live-message",
    "httpx >= 0.28.1",
    "packaging>=26.2",
]
